### ISSUE TITLE
Middle-Earth Map

### ISSUE THREAD

**Issue by CreeperCraft97** [GreatOrator/TolkienCraftII#123]
## Description
The Middle-Earth map is not accurate

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: forge-10.13.4.1566
* TolkienCraft II version: 2.9.5

## Crash report
When pressing 'N' to open the Middle-Earth map (while being in the Middle-Earth dimension) the map shown isn't the same as the playable map. (I downloaded all the extra content).

P.S. Thanks for all the work. This is an amazing modpack.
![tcii map bug spawn](https://cloud.githubusercontent.com/assets/14940642/19240019/dc0e5964-8f08-11e6-9268-ede3ae215c28.png)
![tcii map bug](https://cloud.githubusercontent.com/assets/14940642/19240018/dbff92e4-8f08-11e6-8b00-316fe03f142a.png)

**Comment by GreatOrator** [comment]
That is correct.  Many of the locations created were placed in areas that made the most sense when building.  Sometimes they could be place at or very near the mod's map locations, sometimes nowhere close.  This is what ultimately facilitated the need for the CustomNPC fast travel system in order to ensure players could find all of the locations.
