### ISSUE TITLE
NEI and Forestry

### ISSUE THREAD

**Issue by AeroyrHwrdd** [GreatOrator/TolkienCraftII#57]
Some of the recipes aren't showing up, some are, some aren't. The ones that aren't are mainly the machines.

**Comment by teagan75** [comment]
Could you give a few specific examples?

**Comment by teagan75** [comment]
Ok re-read your comment, so ,for example, a recipe for the carpenter machine isn't showing up?

**Comment by GreatOrator** [comment]
as of the most recent update the new forestry (4.0) has it's own NEI handlers so it was removed from NEI, That was a decision of the mod dev and I am currently working on how to upgrade since they made radical changes to block ID's which would require players to restart worlds if I update right now.
